server:
  port: 2334
  address: 0.0.0.0

spring:
  main:
    banner-mode: log

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: ${LAVALINK_FREE_PASSWORD:defaultpassword}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      http: false
      local: false
    filters:
      volume: true
      equalizer: false
      karaoke: false
      timescale: false
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false
    bufferDurationMs: 600
    frameBufferDurationMs: 8000
    youtubePlaylistLoadLimit: 1
    opusEncodingQuality: 3
    resamplingQuality: LOW
    trackStuckThresholdMs: 15000
    useSeekGhosting: false
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - ANDROID
      - TVHTML5
      - WEB_REMIX
      - WEB
    WEB:
      poToken: ${YOUTUBE_PO_TOKEN:}
      visitorData: ${YOUTUBE_VISITOR_DATA:}
    WEB_REMIX:
      poToken: ${YOUTUBE_PO_TOKEN:}
      visitorData: ${YOUTUBE_VISITOR_DATA:}
    ANDROID:
      visitorData: ${YOUTUBE_VISITOR_DATA:}
    TVHTML5:
      visitorData: ${YOUTUBE_VISITOR_DATA:}
    oauth2:
      enabled: false

metrics:
  prometheus:
    enabled: false

logging:
  file:
    max-history: 7
    max-size: 500MB
  path: ./logs-free/
  level:
    root: WARN
    lavalink: INFO
